
[custom]
ruleset=🎯 全球直连,local_rule/url/LocalAreaNetwork.list
ruleset=🎯 全球直连,local_rule/url/UnBan.list
ruleset=干净节点选择,local_rule/url/hight.list
ruleset=干净节点选择,local_rule/url/ai.list
ruleset=普通节点选择,local_rule/url/GoogleFCM.list
ruleset=普通节点选择,local_rule/url/ProxyGFWlist.list
ruleset=普通节点选择,local_rule/url/medium.list
ruleset=开放节点选择,local_rule/url/low.list
ruleset=🛑 广告拦截,local_rule/url/BanAD.list
ruleset=🛑 广告拦截,local_rule/url/BanEasyList.list
ruleset=🎯 全球直连,local_rule/url/ChinaDomain.list
ruleset=🎯 全球直连,local_rule/url/ChinaCompanyIp.list
ruleset=🎯 全球直连,local_rule/url/GoogleCN.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL


# 总控池
custom_proxy_group=干净节点选择`select`[]香港节点`[]日本节点`[]自由选择
custom_proxy_group=普通节点选择`select`[]香港节点`[]日本节点`[]龙珠测速`[]宝可梦专线测速`[]宝可梦普通测速`[]自由选择
custom_proxy_group=开放节点选择`select`[]香港节点`[]日本节点`[]龙珠测速`[]宝可梦专线测速`[]宝可梦普通测速`[]自由选择`[]普通节点选择

# 节点指定
custom_proxy_group=香港节点`select`[]量子香港节点`[]龙珠香港节点`[]宝可梦专线香港节点`[]宝可梦普通香港节点
custom_proxy_group=日本节点`select`[]量子日本节点`[]龙珠日本节点`[]宝可梦专线日本节点`[]宝可梦普通日本节点
custom_proxy_group=自由选择`select`[]龙珠香港节点`[]龙珠日本节点`[]龙珠三方节点`[]量子香港节点`[]量子日本节点`[]宝可梦专线香港节点`[]宝可梦专线日本节点`[]宝可梦专线三方节点`[]宝可梦普通香港节点`[]宝可梦普通日本节点`[]宝可梦普通三方节点

# 节点测速
custom_proxy_group=龙珠测速`url-test`[]龙珠香港节点`[]龙珠日本节点`[]龙珠三方节点`http://www.gstatic.com/generate_204`300,1800,100
custom_proxy_group=宝可梦专线测速`url-test`[]宝可梦专线香港节点`[]宝可梦专线日本节点`[]宝可梦专线三方节点`http://www.gstatic.com/generate_204`300,1800,100
custom_proxy_group=宝可梦普通测速`url-test`[]宝可梦普通香港节点`[]宝可梦普通日本节点`[]宝可梦普通三方节点`http://www.gstatic.com/generate_204`300,1800,100

# 核心地区测速池
custom_proxy_group=龙珠香港节点`url-test`!!GROUP=longzhu!!^.*(?:港|HK|Hong Kong).*$`[]兜底`http://www.gstatic.com/generate_204`300,,80
custom_proxy_group=龙珠日本节点`url-test`!!GROUP=longzhu!!^.*(?:日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan).*$`[]兜底`http://www.gstatic.com/generate_204`600,,80
custom_proxy_group=龙珠三方节点`url-test`!!GROUP=longzhu!!^.*(?:美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore).*$`[]兜底`http://www.gstatic.com/generate_204`600,,80
custom_proxy_group=量子香港节点`url-test`!!GROUP=quanx!!^.*(?:港|HK|Hong Kong).*$`[]兜底`http://www.gstatic.com/generate_204`300,,80
custom_proxy_group=量子日本节点`url-test`!!GROUP=quanx!!^.*(?:日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan).*$`[]兜底`http://www.gstatic.com/generate_204`600,,80
custom_proxy_group=宝可梦专线香港节点`url-test`!!GROUP=pokemon!!^(?=.*专线).*(?:港|HK|Hong Kong).*$`[]兜底`http://www.gstatic.com/generate_204`300,,80
custom_proxy_group=宝可梦专线日本节点`url-test`!!GROUP=pokemon!!^(?=.*专线).*(?:日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan).*$`[]兜底`http://www.gstatic.com/generate_204`600,,80
custom_proxy_group=宝可梦专线三方节点`url-test`!!GROUP=pokemon!!^(?=.*专线).*(?:美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore).*$`[]兜底`http://www.gstatic.com/generate_204`600,,80
custom_proxy_group=宝可梦普通香港节点`url-test`!!GROUP=pokemon!!^(?!.*专线).*(?:港|HK|Hong Kong).*$`[]兜底`http://www.gstatic.com/generate_204`300,,80
custom_proxy_group=宝可梦普通日本节点`url-test`!!GROUP=pokemon!!^(?!.*专线).*(?:日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan).*$`[]兜底`http://www.gstatic.com/generate_204`600,,80
custom_proxy_group=宝可梦普通三方节点`url-test`!!GROUP=pokemon!!^(?!.*专线).*(?:美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore).*$`[]兜底`http://www.gstatic.com/generate_204`600,,80

# 全局池
custom_proxy_group=龙珠`select`!!GROUP=longzhu
custom_proxy_group=量子`select`!!GROUP=quanx
custom_proxy_group=宝可梦专线`select`!!GROUP=pokemon!!(?=.*专线)
custom_proxy_group=宝可梦普通`select`!!GROUP=pokemon!!(?!.*专线)


custom_proxy_group=🛑 广告拦截`select`[]DIRECT`[]REJECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]干净节点选择`[]普通节点选择`[]开放节点选择

enable_rule_generator=true
overwrite_original_rules=true
