[custom]
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=干净节点选择,https://raw.githubusercontent.com/switchYello/clash_rule/main/url/hight.list
ruleset=干净节点选择,https://raw.githubusercontent.com/juewuy/ShellClash/master/rules/ai.list
ruleset=普通节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=普通节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=普通节点选择,https://raw.githubusercontent.com/switchYello/clash_rule/main/url/medium.list
ruleset=普通节点选择,https://raw.githubusercontent.com/switchYello/clash_rule/main/url/low.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL


# 总控池
custom_proxy_group=干净节点选择`select`[]1-量子香港`[]1-龙珠香港`[]1-宝可梦专线香港`[]1-宝可梦普通香港`[]1-量子日本`[]1-龙珠日本`[]1-宝可梦专线日本`[]1-宝可梦普通日本
custom_proxy_group=普通节点选择`select`[]1-量子香港`[]1-龙珠香港`[]1-宝可梦专线香港`[]1-宝可梦普通香港`[]1-量子日本`[]1-龙珠日本`[]1-宝可梦专线日本`[]1-宝可梦普通日本`[]2-龙珠测速`[]2-宝可梦专线测速`[]2-宝可梦普通测速


# 节点测速
custom_proxy_group=2-龙珠测速`url-test`[]1-龙珠香港`[]1-龙珠日本`[]1-龙珠三方`http://www.gstatic.com/generate_204`330,1800,100
custom_proxy_group=2-宝可梦专线测速`url-test`[]1-宝可梦专线香港`[]1-宝可梦专线日本`[]1-宝可梦专线三方`http://www.gstatic.com/generate_204`330,1800,100
custom_proxy_group=2-宝可梦普通测速`url-test`[]1-宝可梦普通香港`[]1-宝可梦普通日本`[]1-宝可梦普通三方`http://www.gstatic.com/generate_204`330,1800,100


# 核心地区测速池
custom_proxy_group=1-龙珠香港`url-test`!!GROUP=longzhu!!^.*(?:港|HK|Hong Kong).*$`[]兜底`http://www.gstatic.com/generate_204`300,,80
custom_proxy_group=1-量子香港`url-test`!!GROUP=quanx!!^.*(?:港|HK|Hong Kong).*$`[]兜底`http://www.gstatic.com/generate_204`300,,80
custom_proxy_group=1-宝可梦专线香港`url-test`!!GROUP=pokemon!!^(?=.*专线).*(?:港|HK|Hong Kong).*$`[]兜底`http://www.gstatic.com/generate_204`300,,80
custom_proxy_group=1-宝可梦普通香港`url-test`!!GROUP=pokemon!!^(?!.*专线).*(?:港|HK|Hong Kong).*$`[]兜底`http://www.gstatic.com/generate_204`300,,80

custom_proxy_group=1-龙珠日本`url-test`!!GROUP=longzhu!!^.*(?:日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan).*$`[]兜底`http://www.gstatic.com/generate_204`300,,80
custom_proxy_group=1-量子日本`url-test`!!GROUP=quanx!!^.*(?:日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan).*$`[]兜底`http://www.gstatic.com/generate_204`300,,80
custom_proxy_group=1-宝可梦专线日本`url-test`!!GROUP=pokemon!!^(?=.*专线).*(?:日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan).*$`[]兜底`http://www.gstatic.com/generate_204`300,,80
custom_proxy_group=1-宝可梦普通日本`url-test`!!GROUP=pokemon!!^(?!.*专线).*(?:日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan).*$`[]兜底`http://www.gstatic.com/generate_204`300,,80

custom_proxy_group=1-龙珠三方`url-test`!!GROUP=longzhu!!^.*(?:美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore).*$`[]兜底`http://www.gstatic.com/generate_204`600,,80
custom_proxy_group=1-宝可梦专线三方`url-test`!!GROUP=pokemon!!^(?=.*专线).*(?:美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore).*$`[]兜底`http://www.gstatic.com/generate_204`600,,80
custom_proxy_group=1-宝可梦普通三方`url-test`!!GROUP=pokemon!!^(?!.*专线).*(?:美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore).*$`[]兜底`http://www.gstatic.com/generate_204`600,,80


# 全局池
custom_proxy_group=0-龙珠`select`!!GROUP=longzhu
custom_proxy_group=0-量子`select`!!GROUP=quanx
custom_proxy_group=0-宝可梦`select`!!GROUP=pokemon


custom_proxy_group=🛑 广告拦截`select`[]DIRECT`[]REJECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]干净节点选择`[]普通节点选择

enable_rule_generator=true
overwrite_original_rules=true

